### PR TITLE
win10 uwp template

### PR DESCRIPTION
**Pull request by zhaijialong**
Hi, guys.
I can't generate the store app from win10 uwp template due to the errors in appxmanefest file, this patch fixed it...at least for me. If there is something wrong, please let me know. Thanks. : )

### CODE REVIEW

**Comment by coopp** [comment]
Thanks for the info!  We have a similar fix for this already pending to go in soon.  Just curious, what version of Visual Studio 2015 are you using?

**Comment by coopp** [comment]
I am working to get our pending change pushed very soon.  I am glad that you were able to get unblocked.  Thanks again for letting us know.

**Comment by coopp** [comment]
I just pushed a fix to the repository.

**Comment by stammen** [comment]
@coopp The latest Windows 10 templates are being installed but do not appear in Visual Studio 2015 RC and Windows 10 Build 10030. The templates were installed to C:\Users<username>\Documents\Visual Studio 2015\Templates\ProjectTemplates\Windows\Windows Universal. After both relogging in and restarting, the templates do not appear under New Projects in Visual Studio 2015 RC.

image

Searching for OpenGL in installed templates returns No items found.

**Comment by coopp** [comment]
@stammen I just did this on my test machine and I am seeing the templates just fine after I run the install script.  My machine only has the VS 2015 Community Edition RC installed.

Can you tell me more about your dev configuration? 
- Are there any other versions of VS installed?
- Have the templates ever appeared on this same machine?
- How recent is your Visual Studio 2015 RC install?
- Is your VS the Community Edition from the public download site, or a different build?

I would like to figure out this issue so we can understand any VS template install issues that need addressing.

**Comment by austinkinross** [comment]
The templates require Windows SDK 10069 and above, which might need to be run on Windows build 10069 or above.

Could you check which version of the Windows SDK you have installed? If you have below 10069, could you install the 10069 SDK (or above)? If you already have 10069 or above, could you update to a more recent build of Windows (10069+)?

Thanks,
Austin

**Comment by stammen** [comment]
@austinkinross Sorry. I had a typo in my last post. I am using the most current publicly available build of Windows from Windows Insider slow track. It is Build version 10130.

**Comment by stammen** [comment]
@coopp Here are the answers to your questions.

Are there any other versions of VS installed? No

Have the templates ever appeared on this same machine? Yes

How recent is your Visual Studio 2015 RC install? Yesterday. I did a clean install of Windows 10130 and Visual Studio 2015 RC yesterday. I used the latest templates and install script from Angle commit fe38fb27c52eb18ca8931818cf2e4a916c5c5e05

Is your VS the Community Edition from the public download site, or a different build? Public download

**Comment by coopp** [comment]
Great!  Thanks!  I will take some time today to reinstall my test machine to match your configuration.  I downloaded my VS community last week and there could have been more changes in between then and now that I would like to eliminate.

I will post my findings to this thread once I finish my test machine test.

**Comment by coopp** [comment]
Just finished a clean install of Windows 10 Preview release build 10130, and new download/install of Visual Studio 2015 Community RC (14.0.22823.1  D14REL).  Ran the template install script and the templates show up in the new project dialog.

I cannot repro the issue you are seeing. :(

**Comment by stammen** [comment]
Thanks. I guess I will do a reinstall of the OS and Visual Studio 2015 to see if the problem goes away.

**Comment by zhaijialong** [comment]
@coopp I'm using the latest 2015 community RC and windows 10 insider preview build 10130. Thanks.

**Pull request closed without merging**
